// render/vfx.js — weapon & explosion VFX on Blender-rendered textures.
//
// Assets (public/vfx, generated by backend/blender/scripts/vfx_textures.py,
// shipped as lossy WebP — PNG masters are 10× larger):
//   fireball_8x8            64-frame Cycles fireball flipbook (4096²)
//   smoke_8x8               64-frame smoke plume flipbook (4096²)
//   photo_flash_<w>         photo-real muzzle flashes, luma-keyed to alpha (2048²)
//   photo_explosion_hero    photo-real detonation frame (first 160 ms overlay)
//   shockwave / scorch / spark / ember
//   cracks / bullet_chip / glass_shard / splinter   (surface hits + facade scorching)
//
// Everything is drawn through a handful of INSTANCED flipbook batches
// (one draw call per texture, camera-facing quads built in the vertex
// shader, frame-blended) so a 40-particle explosion costs ~6 draws.
// All batches + the two fx PointLights exist from construction, so the
// pre-match `renderer.compile` warm-up compiles every VFX shader and
// uploads every texture before the first shot — nothing compiles
// mid-fight.
import * as THREE from 'three';

export const VFX_BASE = '/vfx';

const VERT = /* glsl */`
  attribute vec3 iPos; attribute float iSize; attribute float iFrame; attribute float iAlpha; attribute float iRot; attribute vec3 iTint;
  uniform vec2 uGrid;
  varying vec2 vUvA; varying vec2 vUvB; varying float vMix; varying float vAlpha; varying vec3 vTint;
  void main() {
    float c = cos(iRot), s = sin(iRot);
    vec2 corner = vec2(position.x * c - position.y * s, position.x * s + position.y * c) * iSize;
    vec4 mv = modelViewMatrix * vec4(iPos, 1.0);
    mv.xy += corner;
    gl_Position = projectionMatrix * mv;
    float frames = uGrid.x * uGrid.y;
    float f0 = clamp(floor(iFrame), 0.0, frames - 1.0);
    float f1 = min(f0 + 1.0, frames - 1.0);
    vMix = clamp(iFrame - f0, 0.0, 1.0);
    vec2 cell = 1.0 / uGrid;
    vec2 c0 = vec2(mod(f0, uGrid.x), floor(f0 / uGrid.x));
    vec2 c1 = vec2(mod(f1, uGrid.x), floor(f1 / uGrid.x));
    vUvA = vec2((c0.x + uv.x) * cell.x, 1.0 - (c0.y + 1.0 - uv.y) * cell.y);
    vUvB = vec2((c1.x + uv.x) * cell.x, 1.0 - (c1.y + 1.0 - uv.y) * cell.y);
    vAlpha = iAlpha; vTint = iTint;
  }`;

const FRAG = /* glsl */`
  uniform sampler2D uMap;
  varying vec2 vUvA; varying vec2 vUvB; varying float vMix; varying float vAlpha; varying vec3 vTint;
  void main() {
    vec4 a = texture2D(uMap, vUvA);
    vec4 b = texture2D(uMap, vUvB);
    vec4 c = mix(a, b, vMix);
    gl_FragColor = vec4(c.rgb * vTint, c.a * vAlpha);
    #include <tonemapping_fragment>
    #include <colorspace_fragment>
  }`;

// One instanced batch = one texture (atlas or single sprite) + a pool
// of particles. `blend`: 'add' (fire, flashes, sparks) or 'alpha' (smoke).
class FlipbookBatch {
  constructor(scene, texture, cols, rows, capacity, blend, { renderOrder = 10 } = {}) {
    this.cols = cols; this.rows = rows; this.frames = cols * rows; this.capacity = capacity;
    const geo = new THREE.InstancedBufferGeometry();
    const plane = new THREE.PlaneGeometry(1, 1);
    geo.setIndex(plane.index);
    geo.setAttribute('position', plane.attributes.position);
    geo.setAttribute('uv', plane.attributes.uv);
    this.aPos = new THREE.InstancedBufferAttribute(new Float32Array(capacity * 3), 3);
    this.aSize = new THREE.InstancedBufferAttribute(new Float32Array(capacity), 1);
    this.aFrame = new THREE.InstancedBufferAttribute(new Float32Array(capacity), 1);
    this.aAlpha = new THREE.InstancedBufferAttribute(new Float32Array(capacity), 1);
    this.aRot = new THREE.InstancedBufferAttribute(new Float32Array(capacity), 1);
    this.aTint = new THREE.InstancedBufferAttribute(new Float32Array(capacity * 3), 3);
    for (const a of [this.aPos, this.aSize, this.aFrame, this.aAlpha, this.aRot, this.aTint]) a.setUsage(THREE.DynamicDrawUsage);
    geo.setAttribute('iPos', this.aPos); geo.setAttribute('iSize', this.aSize); geo.setAttribute('iFrame', this.aFrame);
    geo.setAttribute('iAlpha', this.aAlpha); geo.setAttribute('iRot', this.aRot); geo.setAttribute('iTint', this.aTint);
    this.material = new THREE.ShaderMaterial({
      vertexShader: VERT, fragmentShader: FRAG,
      uniforms: { uMap: { value: texture }, uGrid: { value: new THREE.Vector2(cols, rows) } },
      transparent: true, depthWrite: false, depthTest: true,
      blending: blend === 'add' ? THREE.AdditiveBlending : THREE.NormalBlending,
    });
    this.material.userData.noBatch = true;
    this.mesh = new THREE.Mesh(geo, this.material);
    this.mesh.frustumCulled = false;          // particles span the map; count is tiny anyway
    this.mesh.renderOrder = renderOrder;
    this.mesh.name = 'vfxBatch';
    this.mesh.userData.noBatch = true;
    geo.instanceCount = 0;
    scene.add(this.mesh);
    this.items = [];
  }

  // Particle record: { x,y,z, vx,vy,vz, life, maxLife, size0, size1, rot, rotV,
  //   frame0, frameEnd, alpha0, alpha1, tint:[r,g,b], grav, drag, fadeIn, floorY }
  spawn(p) {
    if (this.items.length >= this.capacity) this.items.shift();
    p.life = 0;
    this.items.push(p);
    return p;
  }

  update(dt) {
    const items = this.items;
    let n = 0;
    for (let i = 0; i < items.length; i++) {
      const p = items[i];
      p.life += dt;
      if (p.life >= p.maxLife) continue;
      const k = p.life / p.maxLife;
      if (p.grav) p.vy -= p.grav * dt;
      if (p.drag) { const d = Math.exp(-p.drag * dt); p.vx *= d; p.vy *= d; p.vz *= d; }
      p.x += p.vx * dt; p.y += p.vy * dt; p.z += p.vz * dt;
      if (p.floorY != null && p.y < p.floorY) { p.y = p.floorY; p.vy = Math.abs(p.vy) * 0.25; p.vx *= 0.6; p.vz *= 0.6; }
      p.rot += p.rotV * dt;
      const ease = p.ease === 'out' ? 1 - (1 - k) * (1 - k) : (p.ease === 'in' ? k * k : k);
      const size = p.size0 + (p.size1 - p.size0) * ease;
      let alpha = p.alpha0 + (p.alpha1 - p.alpha0) * k;
      if (p.fadeIn && p.life < p.fadeIn) alpha *= p.life / p.fadeIn;
      if (p.fadeOut && p.maxLife - p.life < p.fadeOut) alpha *= (p.maxLife - p.life) / p.fadeOut;
      const frame = p.frame0 + (p.frameEnd - p.frame0) * k;
      items[n] = p;
      this.aPos.setXYZ(n, p.x, p.y, p.z);
      this.aSize.setX(n, size);
      this.aFrame.setX(n, frame);
      this.aAlpha.setX(n, Math.max(0, alpha));
      this.aRot.setX(n, p.rot);
      this.aTint.setXYZ(n, p.tint[0], p.tint[1], p.tint[2]);
      n++;
    }
    items.length = n;
    this.mesh.geometry.instanceCount = n;
    if (n) for (const a of [this.aPos, this.aSize, this.aFrame, this.aAlpha, this.aRot, this.aTint]) a.needsUpdate = true;
  }

  dispose() {
    this.mesh.parent?.remove(this.mesh);
    this.mesh.geometry.dispose(); this.material.dispose();
  }
}

const WEAPON_FLASH = {
  pistol:    { tex: 'pistol',  size: 0.55, life: 0.07, light: 6,  color: 0xffe6c0, smoke: 0.35 },
  tec9:      { tex: 'pistol',  size: 0.5,  life: 0.06, light: 6,  color: 0xffe6c0, smoke: 0.3 },
  ak47:      { tex: 'ak47',    size: 0.95, life: 0.075, light: 10, color: 0xffc070, smoke: 0.55 },
  ak47_auto: { tex: 'ak47',    size: 0.95, life: 0.075, light: 10, color: 0xffc070, smoke: 0.55 },
  shotgun:   { tex: 'shotgun', size: 1.45, life: 0.11, light: 16, color: 0xff9a40, smoke: 1.4 },
  rpg:       { tex: 'rpg',     size: 2.1,  life: 0.18, light: 22, color: 0xff7a30, smoke: 2.6 },
};

// Per-surface bullet impact recipe (render/surfaces.js decides the surface).
//   dust: puff size (0 = none) · sparks: count · chips: debris count on the
//   `chipBatch` (splinters / shards) · decal: pockmark size (0 = none).
export const SURFACE_FX = {
  concrete: { dust: 0.9,  dustTint: [0.62, 0.6, 0.57], dustAlpha: 0.55, dustLife: 0.6, sparks: 3,  sparkTint: [1, 0.8, 0.5],   chips: 6,  chipBatch: 'splinters', chipTint: [0.58, 0.56, 0.53], chipSize: 0.9, decal: 0.18, decalAlpha: 0.8,  decalColor: 0xffffff, light: 0 },
  dirt:     { dust: 1.15, dustTint: [0.46, 0.37, 0.27], dustAlpha: 0.6,  dustLife: 0.8, sparks: 0,  sparkTint: [1, 1, 1],       chips: 6,  chipBatch: 'splinters', chipTint: [0.42, 0.32, 0.22], chipSize: 0.8, decal: 0.28, decalAlpha: 0.6,  decalColor: 0x5a4632, light: 0 },
  metal:    { dust: 0.35, dustTint: [0.72, 0.72, 0.72], dustAlpha: 0.3,  dustLife: 0.4, sparks: 14, sparkTint: [1, 0.9, 0.6],   chips: 0,  chipBatch: 'splinters', chipTint: [1, 1, 1],          chipSize: 1,   decal: 0.12, decalAlpha: 0.5,  decalColor: 0xffffff, light: 4, lightColor: 0xffd090 },
  wood:     { dust: 0.7,  dustTint: [0.64, 0.52, 0.36], dustAlpha: 0.5,  dustLife: 0.6, sparks: 0,  sparkTint: [1, 1, 1],       chips: 8,  chipBatch: 'splinters', chipTint: [1, 1, 1],          chipSize: 1.1, decal: 0.2,  decalAlpha: 0.8,  decalColor: 0x6b4a2a, light: 0 },
  glass:    { dust: 0,    dustTint: [1, 1, 1],          dustAlpha: 0,    dustLife: 0.3, sparks: 3,  sparkTint: [1, 1, 1],       chips: 12, chipBatch: 'shards',    chipTint: [0.9, 0.97, 1],     chipSize: 1,   decal: 0,    decalAlpha: 0,    decalColor: 0xffffff, light: 0 },
};

const _Z = new THREE.Vector3(0, 0, 1);
const _n = new THREE.Vector3();
const _t = new THREE.Vector3();
const _b = new THREE.Vector3();
// Orthonormal tangent frame around a normal (for spreading debris / decals).
function frame(nx, ny, nz) {
  _n.set(nx, ny, nz).normalize();
  _t.set(Math.abs(_n.y) > 0.9 ? 1 : 0, Math.abs(_n.y) > 0.9 ? 0 : 1, 0).cross(_n).normalize();
  _b.crossVectors(_n, _t);
  return { n: _n, t: _t, b: _b };
}

// Pool of surface-aligned decal planes (wall scorch, cracks, bullet chips).
class DecalPool {
  constructor(scene, texture, count, { renderOrder = 3, color = 0xffffff } = {}) {
    this.items = []; this.cursor = 0;
    const geo = DecalPool.geo || (DecalPool.geo = new THREE.PlaneGeometry(1, 1));
    for (let i = 0; i < count; i++) {
      const m = new THREE.Mesh(geo, new THREE.MeshBasicMaterial({ map: texture, color, transparent: true, opacity: 0, depthWrite: false, polygonOffset: true, polygonOffsetFactor: -4, polygonOffsetUnits: -4 }));
      m.visible = false; m.renderOrder = renderOrder; m.userData.noBatch = true; m.userData.prewarm = true;
      scene.add(m);
      this.items.push({ m, life: 0, maxLife: 0, alpha: 1 });
    }
  }
  place(x, y, z, nx, ny, nz, size, { alpha = 1, life = 25, color = 0xffffff, roll = Math.random() * Math.PI * 2 } = {}) {
    const it = this.items[this.cursor++ % this.items.length];
    const m = it.m;
    _n.set(nx, ny, nz).normalize();
    m.position.set(x + _n.x * 0.025, y + _n.y * 0.025, z + _n.z * 0.025);
    m.quaternion.setFromUnitVectors(_Z, _n);
    m.rotateZ(roll);
    m.scale.set(size, size, 1);
    m.material.opacity = alpha; m.material.color.setHex(color);
    m.visible = true; it.life = 0; it.maxLife = life; it.alpha = alpha;
    return it;
  }
  update(dt) {
    for (const it of this.items) {
      if (!it.m.visible) continue;
      it.life += dt;
      if (it.life >= it.maxLife) { it.m.visible = false; it.m.material.opacity = 0; continue; }
      const left = it.maxLife - it.life;
      if (left < 4) it.m.material.opacity = it.alpha * (left / 4);
    }
  }
  get active() { return this.items.filter((it) => it.m.visible).length; }
  dispose(scene) { for (const it of this.items) { scene.remove(it.m); it.m.material.dispose(); } }
}

export class VfxSystem {
  constructor(scene, { manager = null, base = VFX_BASE } = {}) {
    this.scene = scene;
    this.ready = false;
    this.time = 0;
    const loader = new THREE.TextureLoader(manager || undefined);
    const tex = (name) => {
      const t = loader.load(`${base}/${name}.webp`, () => { t.needsUpdate = true; });
      t.colorSpace = THREE.SRGBColorSpace;
      t.wrapS = t.wrapT = THREE.ClampToEdgeWrapping;
      t.anisotropy = 4;
      t.generateMipmaps = true;
      return t;
    };
    this.tex = {
      fire: tex('fireball_8x8'), smoke: tex('smoke_8x8'), hero: tex('photo_explosion_hero'),
      shockwave: tex('shockwave'), scorch: tex('scorch'), spark: tex('spark'), ember: tex('ember'),
      pistol: tex('photo_flash_pistol'), ak47: tex('photo_flash_ak47'), shotgun: tex('photo_flash_shotgun'), rpg: tex('photo_flash_rpg'),
      cracks: tex('cracks'), chip: tex('bullet_chip'), shard: tex('glass_shard'), splinter: tex('splinter'),
    };
    this.fire = new FlipbookBatch(scene, this.tex.fire, 8, 8, 24, 'add', { renderOrder: 12 });
    this.smoke = new FlipbookBatch(scene, this.tex.smoke, 8, 8, 160, 'alpha', { renderOrder: 9 });
    this.hero = new FlipbookBatch(scene, this.tex.hero, 1, 1, 8, 'add', { renderOrder: 13 });
    this.sparks = new FlipbookBatch(scene, this.tex.spark, 1, 1, 200, 'add', { renderOrder: 11 });
    this.embers = new FlipbookBatch(scene, this.tex.ember, 1, 1, 120, 'alpha', { renderOrder: 10 });
    // Surface debris — wood splinters / concrete chips (tinted) and glass shards.
    this.splinters = new FlipbookBatch(scene, this.tex.splinter, 1, 1, 160, 'alpha', { renderOrder: 10 });
    this.shards = new FlipbookBatch(scene, this.tex.shard, 1, 1, 160, 'alpha', { renderOrder: 10 });
    this.flash = {};
    for (const w of ['pistol', 'ak47', 'shotgun', 'rpg']) this.flash[w] = new FlipbookBatch(scene, this.tex[w], 1, 1, 12, 'add', { renderOrder: 14 });

    // Surface-aligned decals: facade scorch + cracks (blasts), bullet chips.
    this.wallScorches = new DecalPool(scene, this.tex.scorch, 12, { renderOrder: 2 });
    this.cracks = new DecalPool(scene, this.tex.cracks, 12, { renderOrder: 3 });
    this.chips = new DecalPool(scene, this.tex.chip, 64, { renderOrder: 3 });

    // Ground-aligned meshes: shockwave rings + scorch decals (pooled).
    this.rings = [];
    const ringGeo = new THREE.PlaneGeometry(1, 1);
    for (let i = 0; i < 6; i++) {
      const m = new THREE.Mesh(ringGeo, new THREE.MeshBasicMaterial({ map: this.tex.shockwave, transparent: true, opacity: 0, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide }));
      m.rotation.x = -Math.PI / 2; m.renderOrder = 8; m.userData.noBatch = true; m.userData.prewarm = true;
      scene.add(m);
      this.rings.push({ m, life: 0, maxLife: 0, size: 0 });
    }
    this.scorches = [];
    for (let i = 0; i < 12; i++) {
      const m = new THREE.Mesh(ringGeo, new THREE.MeshBasicMaterial({ map: this.tex.scorch, transparent: true, opacity: 0, depthWrite: false }));
      m.rotation.x = -Math.PI / 2; m.renderOrder = 2; m.userData.noBatch = true; m.userData.prewarm = true;
      scene.add(m);
      this.scorches.push({ m, life: 0, maxLife: 0 });
    }
    this._scorchCursor = 0; this._ringCursor = 0;

    // Two dynamic lights that exist from frame 0 (constant light count):
    // A = muzzle pop, B = explosion flash.
    this.lights = [0, 1].map((i) => {
      const l = new THREE.PointLight(0xffc080, 0, 14, 1.8);
      l.name = i === 0 ? 'fxMuzzleLight' : 'fxBlastLight';
      l.userData.dynamic = true; l.castShadow = false;
      scene.add(l);
      return { l, intensity: 0, decay: 0 };
    });
    this.ready = true;
  }

  // ── emitters ─────────────────────────────────────────────────────
  muzzleFlash(x, y, z, ux, uy, uz, wpn) {
    const cfg = WEAPON_FLASH[wpn] || WEAPON_FLASH.pistol;
    const batch = this.flash[cfg.tex];
    const fx = x + ux * 0.25, fy = y + uy * 0.25, fz = z + uz * 0.25;
    const rot = Math.random() * Math.PI * 2;
    batch.spawn({ x: fx, y: fy, z: fz, vx: ux * 1.5, vy: uy * 1.5, vz: uz * 1.5, maxLife: cfg.life, size0: cfg.size * 0.7, size1: cfg.size * 1.15, ease: 'out',
      rot, rotV: 0, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 0, tint: [1, 1, 1] });
    // hot core — second, smaller, brighter copy at a different roll
    batch.spawn({ x: fx, y: fy, z: fz, vx: 0, vy: 0, vz: 0, maxLife: cfg.life * 0.6, size0: cfg.size * 0.45, size1: cfg.size * 0.3,
      rot: rot + 1.3, rotV: 0, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 0, tint: [1, 0.95, 0.85] });
    if (cfg.smoke > 0.2) {
      const n = cfg.smoke > 1 ? 3 : 1;
      for (let i = 0; i < n; i++) {
        this.smoke.spawn({ x: fx + ux * 0.2, y: fy + uy * 0.2, z: fz + uz * 0.2,
          vx: ux * (1.2 + Math.random()) + (Math.random() - 0.5) * 0.5, vy: 0.6 + Math.random() * 0.5, vz: uz * (1.2 + Math.random()) + (Math.random() - 0.5) * 0.5,
          maxLife: 0.7 + cfg.smoke * 0.35, size0: 0.25 * cfg.smoke, size1: 0.9 * cfg.smoke, drag: 2.5,
          rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 1.5, frame0: 8, frameEnd: 63, alpha0: 0.45, alpha1: 0, tint: [0.8, 0.8, 0.8] });
      }
    }
    this._pulse(0, fx, fy, fz, cfg.light, cfg.color, 18);
  }

  explosion(x, y, z, { scale = 1, wpn = 'rpg' } = {}) {
    const S = scale * (wpn === 'pipebomb' ? 1.15 : 1);
    const gy = Math.max(0.05, y);
    // photo-real detonation frame — punchy first 140 ms
    this.hero.spawn({ x, y: gy + 1.2 * S, z, vx: 0, vy: 1.5, vz: 0, maxLife: 0.16, size0: 2.2 * S, size1: 5.2 * S, ease: 'out',
      rot: Math.random() * 6.28, rotV: 0, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 0, tint: [1, 1, 1] });
    // Cycles fireball flipbook — 64 frames over ~0.8 s, rising
    for (let i = 0; i < 3; i++) {
      const j = i * 0.35;
      this.fire.spawn({ x: x + (Math.random() - 0.5) * 0.8 * S, y: gy + 0.9 * S + j, z: z + (Math.random() - 0.5) * 0.8 * S,
        vx: (Math.random() - 0.5) * 0.8, vy: 1.6 + Math.random(), vz: (Math.random() - 0.5) * 0.8, drag: 1.2,
        maxLife: 0.75 + i * 0.12, size0: 2.4 * S, size1: 6.2 * S, ease: 'out',
        rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 0.8, frame0: 0, frameEnd: 63, alpha0: 1, alpha1: 0.9, tint: [1, 1, 1] });
    }
    // Smoke plume — dark, rising, drifting apart, lingers
    for (let i = 0; i < 9; i++) {
      const a = Math.random() * 6.28, r = Math.random() * 1.2 * S;
      this.smoke.spawn({ x: x + Math.cos(a) * r, y: gy + 0.6 * S + Math.random() * 1.2, z: z + Math.sin(a) * r,
        vx: Math.cos(a) * (1.2 + Math.random()), vy: 2.2 + Math.random() * 1.6, vz: Math.sin(a) * (1.2 + Math.random()), drag: 1.1,
        maxLife: 2.6 + Math.random() * 1.4, size0: 1.6 * S, size1: 5.5 * S, ease: 'out', fadeIn: 0.12,
        rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 0.9, frame0: Math.random() * 6, frameEnd: 63, alpha0: 0.85, alpha1: 0, tint: [0.32, 0.3, 0.29] });
    }
    // Sparks + embers — fast, gravity, floor bounce
    for (let i = 0; i < 26; i++) {
      const a = Math.random() * 6.28, el = 0.15 + Math.random() * 1.2, sp = 7 + Math.random() * 9;
      this.sparks.spawn({ x, y: gy + 0.4, z, vx: Math.cos(a) * Math.cos(el) * sp, vy: Math.sin(el) * sp, vz: Math.sin(a) * Math.cos(el) * sp, grav: 16, drag: 0.6,
        maxLife: 0.35 + Math.random() * 0.45, size0: 0.28 * S, size1: 0.06, rot: a, rotV: 0, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 0, tint: [1, 0.85, 0.6] });
    }
    for (let i = 0; i < 14; i++) {
      const a = Math.random() * 6.28, el = 0.3 + Math.random() * 1.1, sp = 4 + Math.random() * 6;
      this.embers.spawn({ x, y: gy + 0.5, z, vx: Math.cos(a) * Math.cos(el) * sp, vy: Math.sin(el) * sp, vz: Math.sin(a) * Math.cos(el) * sp, grav: 13, drag: 0.4, floorY: 0.04,
        maxLife: 0.9 + Math.random() * 0.9, size0: 0.22 * S, size1: 0.12 * S, rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 12, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 0, fadeOut: 0.3, tint: [1, 1, 1] });
    }
    // Shockwave ring on the ground + scorch decal
    const ring = this.rings[this._ringCursor++ % this.rings.length];
    ring.m.position.set(x, gy + 0.08, z); ring.life = 0; ring.maxLife = 0.5; ring.size = 9 * S; ring.m.visible = true;
    const sc = this.scorches[this._scorchCursor++ % this.scorches.length];
    sc.m.position.set(x, 0.03, z); sc.m.rotation.z = Math.random() * 6.28; sc.m.scale.set(4.2 * S, 4.2 * S, 1); sc.life = 0; sc.maxLife = 28; sc.m.visible = true; sc.m.material.opacity = 0.92;
    this._pulse(1, x, gy + 1.5, z, 48 * S, 0xff8a3a, 5.5);
  }

  // RPG exhaust: smoke ribbon + ember behind the round each frame.
  rocketTrail(x, y, z, vx, vy, vz, dt) {
    this._trailAcc = (this._trailAcc || 0) + dt;
    if (this._trailAcc < 0.028) return;
    this._trailAcc = 0;
    const sp = Math.hypot(vx, vy, vz) || 1;
    const bx = x - vx / sp * 0.5, by = y - vy / sp * 0.5, bz = z - vz / sp * 0.5;
    this.smoke.spawn({ x: bx, y: by, z: bz, vx: (Math.random() - 0.5) * 0.6, vy: 0.4 + Math.random() * 0.4, vz: (Math.random() - 0.5) * 0.6, drag: 1.5,
      maxLife: 0.9 + Math.random() * 0.5, size0: 0.28, size1: 1.3, ease: 'out', rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 2,
      frame0: 4, frameEnd: 63, alpha0: 0.55, alpha1: 0, tint: [0.78, 0.76, 0.74] });
    this.sparks.spawn({ x: bx, y: by, z: bz, vx: -vx * 0.08 + (Math.random() - 0.5) * 2, vy: -vy * 0.08 + (Math.random() - 0.5) * 2, vz: -vz * 0.08 + (Math.random() - 0.5) * 2,
      maxLife: 0.12 + Math.random() * 0.1, size0: 0.4, size1: 0.1, rot: 0, rotV: 0, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 0, tint: [1, 0.7, 0.35] });
  }

  // Generic hot pop (pipe-bomb bounce, fuse) — routed to the blast light.
  pulse(x, y, z, intensity, color = 0xffb040) { this._pulse(1, x, y, z, intensity, color, 10); }

  // ── surfaces ─────────────────────────────────────────────────────
  // Bullet strike on a classified surface (render/surfaces.js): dust
  // puff off the face, sparks, chips/splinters/shards with gravity, a
  // pockmark decal aligned to the face normal, optional light pop.
  surfaceHit(x, y, z, nx, ny, nz, surf = 'concrete', { big = false } = {}) {
    const P = SURFACE_FX[surf] || SURFACE_FX.concrete;
    const k = big ? 1.6 : 1;
    const { n, t, b } = frame(nx, ny, nz);
    const ox = x + n.x * 0.06, oy = y + n.y * 0.06, oz = z + n.z * 0.06;
    if (P.dust > 0) {
      this.smoke.spawn({ x: ox, y: oy, z: oz, vx: n.x * 1.4 + (Math.random() - 0.5) * 0.6, vy: n.y * 1.4 + 0.45, vz: n.z * 1.4 + (Math.random() - 0.5) * 0.6, drag: 3.2,
        maxLife: P.dustLife, size0: P.dust * 0.3 * k, size1: P.dust * 1.15 * k, ease: 'out', rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 2,
        frame0: 6, frameEnd: 63, alpha0: P.dustAlpha, alpha1: 0, tint: P.dustTint });
    }
    const nSparks = Math.round(P.sparks * k);
    for (let i = 0; i < nSparks; i++) {
      const a = Math.random() * 6.28, spread = 0.25 + Math.random() * 0.9, sp = (surf === 'metal' ? 5 : 2.5) + Math.random() * (surf === 'metal' ? 8 : 3);
      const dx = n.x + (t.x * Math.cos(a) + b.x * Math.sin(a)) * spread, dy = n.y + (t.y * Math.cos(a) + b.y * Math.sin(a)) * spread, dz = n.z + (t.z * Math.cos(a) + b.z * Math.sin(a)) * spread;
      this.sparks.spawn({ x: ox, y: oy, z: oz, vx: dx * sp, vy: dy * sp, vz: dz * sp, grav: 14, drag: 0.8, floorY: 0.03,
        maxLife: 0.14 + Math.random() * 0.3, size0: (surf === 'glass' ? 0.1 : 0.16) * k, size1: 0.03, rot: a, rotV: 0, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 0, tint: P.sparkTint });
    }
    const nChips = Math.round(P.chips * k);
    const batch = this[P.chipBatch] || this.splinters;
    for (let i = 0; i < nChips; i++) {
      const a = Math.random() * 6.28, spread = 0.3 + Math.random() * 1.1, sp = 1.5 + Math.random() * 3.5;
      const dx = n.x + (t.x * Math.cos(a) + b.x * Math.sin(a)) * spread, dy = n.y + (t.y * Math.cos(a) + b.y * Math.sin(a)) * spread + 0.4, dz = n.z + (t.z * Math.cos(a) + b.z * Math.sin(a)) * spread;
      const sz = (0.06 + Math.random() * 0.1) * P.chipSize * k;
      batch.spawn({ x: ox, y: oy, z: oz, vx: dx * sp, vy: dy * sp, vz: dz * sp, grav: 12, drag: 0.6, floorY: 0.03,
        maxLife: 0.6 + Math.random() * 0.7, size0: sz, size1: sz * 0.9, rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 14, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 1, fadeOut: 0.25, tint: P.chipTint });
    }
    if (P.decal > 0) this.chips.place(x, y, z, nx, ny, nz, P.decal * (0.8 + Math.random() * 0.5) * k, { alpha: P.decalAlpha, life: 24, color: P.decalColor });
    if (P.light > 0) this._pulse(0, ox + n.x * 0.15, oy + n.y * 0.15, oz + n.z * 0.15, P.light, P.lightColor || 0xffd090, 26);
  }

  // Blast mark on a vertical face: scorch + (concrete) cracks + dust
  // rolling off the wall. `size` is the decal diameter in metres.
  wallScorch(x, y, z, nx, ny, nz, size = 3, { cracks = true } = {}) {
    this.wallScorches.place(x, y, z, nx, ny, nz, size, { alpha: 0.9, life: 28, color: 0xffffff });
    if (cracks) this.cracks.place(x, y, z, nx, ny, nz, size * 0.9, { alpha: 0.85, life: 40 });
    const { n } = frame(nx, ny, nz);
    for (let i = 0; i < 3; i++) {
      this.smoke.spawn({ x: x + n.x * 0.2 + (Math.random() - 0.5) * size * 0.4, y: y + (Math.random() - 0.5) * size * 0.4, z: z + n.z * 0.2 + (Math.random() - 0.5) * size * 0.4,
        vx: n.x * (1.5 + Math.random()), vy: 0.8 + Math.random() * 0.8, vz: n.z * (1.5 + Math.random()), drag: 1.6,
        maxLife: 1.1 + Math.random() * 0.6, size0: size * 0.2, size1: size * 0.6, ease: 'out', rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 1.5,
        frame0: 6, frameEnd: 63, alpha0: 0.5, alpha1: 0, tint: [0.55, 0.53, 0.5] });
    }
    for (let i = 0; i < 6; i++) {
      this.splinters.spawn({ x: x + (Math.random() - 0.5) * size * 0.5, y: y + (Math.random() - 0.5) * size * 0.5, z: z + (Math.random() - 0.5) * size * 0.5,
        vx: n.x * (2 + Math.random() * 3) + (Math.random() - 0.5) * 2, vy: 1 + Math.random() * 3, vz: n.z * (2 + Math.random() * 3) + (Math.random() - 0.5) * 2, grav: 12, drag: 0.5, floorY: 0.03,
        maxLife: 0.8 + Math.random() * 0.8, size0: 0.08 + Math.random() * 0.1, size1: 0.1, rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 12, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 1, fadeOut: 0.3, tint: [0.5, 0.48, 0.45] });
    }
  }

  // Loose dust puff (debris landing, prop breaking). Replaces the old
  // grey-sphere puffs in destructibles.js.
  dust(x, y, z, scale = 1, tint = [0.6, 0.58, 0.55], alpha = 0.5) {
    this.smoke.spawn({ x, y, z, vx: (Math.random() - 0.5) * 0.8, vy: 0.5 + Math.random() * 0.6, vz: (Math.random() - 0.5) * 0.8, drag: 2.2,
      maxLife: 0.6 + Math.random() * 0.4, size0: 0.3 * scale, size1: 1.3 * scale, ease: 'out', rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 1.5,
      frame0: 4 + Math.random() * 6, frameEnd: 63, alpha0: alpha, alpha1: 0, tint });
  }

  // Prop breaking apart — per-material debris shower + dust.
  debrisBurst(x, y, z, surf = 'wood', count = 8) {
    if (surf === 'glass') { this.glassShatter(x, y, z, { count: count * 2 }); return; }
    const P = SURFACE_FX[surf] || SURFACE_FX.concrete;
    for (let i = 0; i < Math.max(2, Math.round(count * 0.5)); i++) this.dust(x + (Math.random() - 0.5) * 0.8, y + Math.random() * 0.5, z + (Math.random() - 0.5) * 0.8, 1.1, P.dustTint, 0.55);
    if (surf === 'metal') {
      for (let i = 0; i < count * 2; i++) {
        const a = Math.random() * 6.28, el = 0.2 + Math.random() * 1.2, sp = 4 + Math.random() * 7;
        this.sparks.spawn({ x, y, z, vx: Math.cos(a) * Math.cos(el) * sp, vy: Math.sin(el) * sp, vz: Math.sin(a) * Math.cos(el) * sp, grav: 14, drag: 0.7, floorY: 0.03,
          maxLife: 0.2 + Math.random() * 0.4, size0: 0.2, size1: 0.04, rot: a, rotV: 0, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 0, tint: [1, 0.9, 0.6] });
      }
    }
    for (let i = 0; i < count; i++) {
      const a = Math.random() * 6.28, el = 0.25 + Math.random() * 1.1, sp = 2.5 + Math.random() * 4.5;
      const sz = (0.08 + Math.random() * 0.14) * P.chipSize;
      this.splinters.spawn({ x, y, z, vx: Math.cos(a) * Math.cos(el) * sp, vy: Math.sin(el) * sp, vz: Math.sin(a) * Math.cos(el) * sp, grav: 12, drag: 0.5, floorY: 0.03,
        maxLife: 0.9 + Math.random() * 0.9, size0: sz, size1: sz, rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 14, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 1, fadeOut: 0.35, tint: surf === 'metal' ? [0.25, 0.25, 0.27] : P.chipTint });
    }
  }

  // Pane shattering: shards spread over the (w × h) glass face, falling
  // and tumbling, plus a few white glints.
  glassShatter(x, y, z, { w = 1.8, h = 1.8, nx = 0, nz = 1, count = 32 } = {}) {
    const { n, t, b } = frame(nx, 0, nz);
    for (let i = 0; i < count; i++) {
      const u = (Math.random() - 0.5) * w, v = (Math.random() - 0.5) * h;
      const px = x + t.x * u + b.x * v, py = y + t.y * u + b.y * v, pz = z + t.z * u + b.z * v;
      const side = Math.random() < 0.5 ? -1 : 1, sp = 0.6 + Math.random() * 2.2;
      const sz = 0.06 + Math.random() * 0.16;
      this.shards.spawn({ x: px, y: py, z: pz, vx: n.x * side * sp + (Math.random() - 0.5) * 0.8, vy: (Math.random() - 0.3) * 1.5, vz: n.z * side * sp + (Math.random() - 0.5) * 0.8, grav: 12, drag: 0.4, floorY: 0.03,
        maxLife: 0.9 + Math.random() * 1.1, size0: sz, size1: sz, rot: Math.random() * 6.28, rotV: (Math.random() - 0.5) * 16, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 0.9, fadeOut: 0.3, tint: [0.9, 0.97, 1] });
    }
    for (let i = 0; i < 5; i++) {
      this.sparks.spawn({ x: x + (Math.random() - 0.5) * w * 0.6, y: y + (Math.random() - 0.5) * h * 0.6, z, vx: 0, vy: 0, vz: 0,
        maxLife: 0.08 + Math.random() * 0.08, size0: 0.35, size1: 0.05, rot: Math.random() * 3, rotV: 0, frame0: 0, frameEnd: 0, alpha0: 1, alpha1: 0, tint: [1, 1, 1] });
    }
  }

  _pulse(i, x, y, z, intensity, color, decay) {
    const L = this.lights[i];
    L.l.position.set(x, y, z); L.l.color.setHex(color); L.intensity = Math.max(L.intensity, intensity); L.decay = decay;
    L.l.intensity = L.intensity;
  }

  // ── per frame ────────────────────────────────────────────────────
  update(dt) {
    dt = Math.min(0.05, Math.max(0, dt || 0));
    this.time += dt;
    this.fire.update(dt); this.smoke.update(dt); this.hero.update(dt); this.sparks.update(dt); this.embers.update(dt);
    this.splinters.update(dt); this.shards.update(dt);
    for (const w in this.flash) this.flash[w].update(dt);
    this.wallScorches.update(dt); this.cracks.update(dt); this.chips.update(dt);
    for (const r of this.rings) {
      if (!r.m.visible) continue;
      r.life += dt;
      if (r.life >= r.maxLife) { r.m.visible = false; r.m.material.opacity = 0; continue; }
      const k = r.life / r.maxLife, e = 1 - (1 - k) * (1 - k);
      const s = 0.6 + r.size * e;
      r.m.scale.set(s, s, 1);
      r.m.material.opacity = 0.9 * (1 - k);
    }
    for (const s of this.scorches) {
      if (!s.m.visible) continue;
      s.life += dt;
      if (s.life >= s.maxLife) { s.m.visible = false; continue; }
      const left = s.maxLife - s.life;
      if (left < 4) s.m.material.opacity = 0.92 * (left / 4);
    }
    for (const L of this.lights) {
      if (L.intensity <= 0.01) { L.intensity = 0; L.l.intensity = 0; continue; }
      L.intensity *= Math.exp(-L.decay * dt);
      L.l.intensity = L.intensity;
    }
  }

  // Everything that must be hot before the first shot: spawn one of
  // each effect (alpha 0 so nothing shows) so instanceCount > 0 and the
  // material/texture is touched by the next compile pass.
  prewarm() {
    const far = { x: 0, y: -900, z: 0 };
    const z = (b, extra = {}) => b.spawn({ ...far, vx: 0, vy: 0, vz: 0, maxLife: 0.5, size0: 1, size1: 1, rot: 0, rotV: 0, frame0: 0, frameEnd: 0, alpha0: 0, alpha1: 0, tint: [1, 1, 1], ...extra });
    z(this.fire); z(this.smoke); z(this.hero); z(this.sparks); z(this.embers); z(this.splinters); z(this.shards);
    for (const w in this.flash) z(this.flash[w]);
    this.update(0.001);
  }

  dispose() {
    for (const b of [this.fire, this.smoke, this.hero, this.sparks, this.embers, this.splinters, this.shards, ...Object.values(this.flash)]) b.dispose();
    for (const r of this.rings) { this.scene.remove(r.m); r.m.material.dispose(); }
    for (const s of this.scorches) { this.scene.remove(s.m); s.m.material.dispose(); }
    for (const p of [this.wallScorches, this.cracks, this.chips]) p.dispose(this.scene);
    for (const L of this.lights) this.scene.remove(L.l);
    for (const t of Object.values(this.tex)) t.dispose();
  }
}
